update mysql init scripts

diff --git a/dev-db/mysql-init-scripts/files/mysql.initd b/dev-db/mysql-init-scripts/files/mysql.initd
--- a/dev-db/mysql-init-scripts/files/mysql.initd
+++ b/dev-db/mysql-init-scripts/files/mysql.initd
@@ -1,7 +1,7 @@
 #!/sbin/runscript
-# Copyright 1999-2011 Gentoo Foundation
+# Copyright 1999-2013 Gentoo Foundation
 # Distributed under the terms of the GNU General Public License v2
-# $Header: /var/cvsroot/gentoo-x86/dev-db/mysql-init-scripts/files/mysql-5.1.53-init.d,v 1.1 2011/01/13 20:06:06 robbat2 Exp $
+# $Header: /var/cvsroot/gentoo-x86/dev-db/mysql-init-scripts/files/mysql-5.1.67-init.d,v 1.1 2013/01/18 01:51:47 robbat2 Exp $
 
 depend() {
 	use net.lo
@@ -24,6 +24,19 @@ mysql_svcname() {
 }
 
 start() {
+	# Check for old conf.d variables that mean migration was not yet done.
+	set | egrep -sq '^(mysql_slot_|MYSQL_BLOG_PID_FILE|STOPTIMEOUT)'
+	rc=$?
+	# Yes, MYSQL_INIT_I_KNOW_WHAT_I_AM_DOING is a hidden variable.
+	# It does have a use in testing, as it is possible to build a config file
+	# that works with both the old and new init scripts simulateously.
+	if [ "${rc}" = 0 -a -z "${MYSQL_INIT_I_KNOW_WHAT_I_AM_DOING}" ]; then
+		eerror "You have not updated your conf.d for the new mysql-init-scripts-2 revamp."
+		eerror "Not proceeding because it may be dangerous."
+		return 1
+	fi
+
+	# Now we can startup
 	ebegin "Starting $(mysql_svcname)"
 
 	MY_CNF="${MY_CNF:-/etc/${SVCNAME}/my.cnf}"
@@ -52,23 +65,19 @@ start() {
 	fi
 
 	local piddir="${pidfile%/*}"
-	if [ ! -d "$piddir" ] ; then
-		mkdir "$piddir" && \
-		chown mysql "$piddir"
-		rc=$?
-		if [ $rc -ne 0 ]; then
-			eerror "Directory $piddir for pidfile does not exist and cannot be created"
-			return 1
-		fi
+	checkpath -d --owner mysql:mysql --mode 0755 "$piddir"
+	rc=$?
+	if [ $rc -ne 0 ]; then
+		eerror "Directory $piddir for pidfile does not exist and cannot be created"
+		return 1
 	fi
 
 	local startup_timeout=${STARTUP_TIMEOUT:-900}
 	local startup_early_timeout=${STARTUP_EARLY_TIMEOUT:-1000}
 	local tmpnice="${NICE:+"--nicelevel "}${NICE}"
 	local tmpionice="${IONICE:+"--ionice "}${IONICE}"
-
 	start-stop-daemon \
-		${DEBUG/*/"--verbose"} \
+		${DEBUG:+"--verbose"} \
 		--start \
 		--exec "${basedir}"/sbin/mysqld \
 		--pidfile "${pidfile}" \
@@ -77,7 +86,6 @@ start() {
 		${tmpnice} \
 		${tmpionice} \
 		-- --defaults-file="${MY_CNF}" ${MY_ARGS}
-
 	local ret=$?
 	if [ ${ret} -ne 0 ] ; then
 		eend ${ret}
@@ -94,27 +102,17 @@ start() {
 stop() {
 	ebegin "Stopping $(mysql_svcname)"
 
-	MY_CNF="${MY_CNF:-/etc/${SVCNAME}/my.cnf}"
-
 	local pidfile="$(get_options pidfile)"
 	local basedir="$(get_options basedir)"
 	local stop_timeout=${STOP_TIMEOUT:-120}
 
-	if [ -z "${pidfile}" ]; then
-		pidfile=$(get_config "${MY_CNF}" pid-file | tail -n1)
-	fi
-
-	if [ -z "${basedir}" ]; then
-		basedir=$(get_config "${MY_CNF}" basedir | tail -n1)
-	fi
-
 	start-stop-daemon \
-		${DEBUG/*/"--verbose"} \
+		${DEBUG:+"--verbose"} \
 		--stop \
 		--exec "${basedir}"/sbin/mysqld \
 		--pidfile "${pidfile}" \
 		--retry ${stop_timeout}
 	eend $?
 }
+# vim: filetype=gentoo-init-d sw=2 ts=2 sts=2 noet:
 
-# vim: filetype=gentoo-init-d:
